services:
  - type: web
    name: meat-menu-app-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MENU_BASE_URL
        value: https://web-gamma-eosin-99.vercel.app
